In [ ]:
0 ** 0


1.0

In [3]:
import numpy as np
np.dot([1, 2, 3], [4, 5, 6])

np.int64(32)

In [ ]:
np.array([[1, 0, 0], 
          [0, 1, 0], 
          [0, 0, 1], 
          [1, 1, 1]]) @ [1, 2, 1] # matrix mul treats vectors as column vectors.

array([1, 2, 1, 4])

In [ ]:
np.array([[1, 0, 0], 
          [0, 1, 0], 
          [0, 0, 1], 
          [1, 1, 1]]) * [1, 2, 1] # shows broadcasting. This shows that * treats vectors as row vectors.

NameError: name 'np' is not defined

In [53]:
x = np.array([[1, 0, 2], [0, 1, 2], [0, 0, 1]])
x[0:2,2]


array([2, 2])

In [4]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]]) 
x @ x

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [5]:
x * x

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [6]:
x[0:3, 0:3] = 3

In [7]:
x

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [48]:
x[0:2, 0:1] = [[1, 2]]

ValueError: could not broadcast input array from shape (1,2) into shape (2,1)

In [57]:
# note: due to broadcasting rules, a vector in R^n is interpreted as a row vector (1 x n)

x = np.array([[1, 2], [3, 4]])
x * [1, 2]

array([[1, 4],
       [3, 8]])